<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Contact Us Form Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'thank-you-for-contacting-dta.html',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'info@dtainc.us',
		'to' => 'info@dtainc.us'
	),
	'fields' => array(
		'custom_U5290' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name:*',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name:*\' is required.'
			)
		),
		'Email' => array(
			'order' => 3,
			'type' => 'email',
			'label' => 'Email:*',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email:*\' is required.',
				'format' => 'Field \'Email:*\' has an invalid email.'
			)
		),
		'custom_U5294' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Message:*',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U5752' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Company:*',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Company:*\' is required.'
			)
		),
		'custom_U5772' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Work Phone:*',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Work Phone:*\' is required.'
			)
		),
		'custom_U5792' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Cell Phone',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U5812' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Website',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U5852' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Position or Title',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U6052' => array(
			'order' => 5,
			'type' => 'radiogroup',
			'label' => 'What is the main focus of this contact?*',
			'required' => true,
			'optionItems' => array(
				'Assessment Services',
				'Consulting Services',
				'Development Services',
				'Analytics Services',
				'Cloud Deployment Services',
				'Administration Services',
				'Security Services',
				'Other (explain in message field below)'
			),
			'errors' => array(
				'required' => 'Field \'What is the main focus of this contact?*\' is required.',
				'format' => 'Field \'What is the main focus of this contact?*\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
